version: "3.1"

services:
  db:
    image: postgres:16.0-bookworm
    restart: always
    environment:
      POSTGRES_DB: psql
      POSTGRES_USER: psql
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

volumes:
  data:
